### PR TITLE
Release 2.5

### PR DESCRIPTION
**Pull request by ikari7789**
Adds PHP 8.2 and 8.3 support.

### CODE REVIEW

**Comment by mr-feek** [comment]
Hi @philcook -- any chance we could get this merged + a new release cut? I'd love to be able to use php 8.1/8.2 with `brew-php-switch`!

**Comment by danepowell** [comment]
@ikari7789 is there anyone besides Phil who can approve this?

**Comment by vzool** [comment]
+1

**Comment by alfianrehanusa** [comment]
up

**Comment by eleftrik** [comment]
Hi @philcook, could you please review this PR?

If you don't maintain anymore this project, could you please add someone who can handle this project?
Thank you.

**Comment by fhferreira** [comment]
+1

**Comment by Nyholm** [comment]
Im sure @philcook or @ikari7789 would be happy to get some help maintaining this package if someone reach out to them and ask nicely. 

In the meantime, here is how you install the latest (unreleased) version: 

```
brew unlink brew-php-switcher
brew install brew-php-switcher --head
```

**Comment by DannyvdSluijs** [comment]
See https://github.com/philcook/brew-php-switcher/releases/tag/v2.5

**Pull request closed without merging**
