### PR TITLE
Update for new PHP packages from Homebrew

### PR DESCRIPTION
**Pull request by ikari7789**
Homebrew decided to change the way that they manage PHP. It has some big differences, especially in the package names.

See https://github.com/Homebrew/homebrew-php/issues/4721

### CODE REVIEW

**Comment by ikari7789** [comment]
This should probably be released as v2.0.

**Comment by philcook** [comment]
@ikari7789 thanks for your help making brew php switcher better. I am going to merge this now and as suggested release version 2.0

**Comment by ikari7789** [comment]
Thanks a lot! I have fixes for some other issues cooking as well, but may take me a day or two to find time to clean it up.

**Comment by philcook** [comment]
@pauliuslukosiunas because redis is language agnostic (see https://redis.io/clients) therefore its not tied to php.
To get redis installed I would assume its a simple `brew install redis` and then link the module in the php.ini 
When I say I assume this is because I myself don't use redis so please feel free to try and write back your discoveries.

**Pull request merged**
