### PR TITLE
PHP 7.2 support

### PR DESCRIPTION
**Pull request by SMillerDev**
I thought this was all that was needed looking at the 7.1 commit

### CODE REVIEW

**Comment by SMillerDev** [comment]
Travis doesn't seem to be failing due to a change in my code, some review indicates it's rvm related

**Comment by SMillerDev** [comment]
@philcook got time to look at this?

**Comment by madmatt** [comment]
I can confirm this PR works for me.

**Comment by madmatt** [comment]
For those that arrive here from Google, you can just hand-edit `/usr/local/Cellar/brew-php-switcher/1.6/bin/phpswitch.sh` - make the two-line change as per the file in this PR: https://github.com/philcook/brew-php-switcher/pull/31/files#diff-3697793acf71fff9a5d295b5d275e765

**Comment by madmatt** [comment]
Awesome, thanks @philcook!

**Pull request closed without merging**
